/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PosApp {
    }
}
declare global {
    interface HTMLPosAppElement extends Components.PosApp, HTMLStencilElement {
    }
    var HTMLPosAppElement: {
        prototype: HTMLPosAppElement;
        new (): HTMLPosAppElement;
    };
    interface HTMLElementTagNameMap {
        "pos-app": HTMLPosAppElement;
    }
}
declare namespace LocalJSX {
    interface PosApp {
    }
    interface IntrinsicElements {
        "pos-app": PosApp;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pos-app": LocalJSX.PosApp & JSXBase.HTMLAttributes<HTMLPosAppElement>;
        }
    }
}
